### PR TITLE
Update Russian.ini RC4 sample 3

### PR DESCRIPTION
**Pull request by wvxwxvw**

### CODE REVIEW

**Comment by SeaHOH** [comment]
If you edit language files in web page, you will see a warning:
edit_warning

The right method is use upload function:
upload_files

**Comment by SeaHOH** [comment]
You made the same mistake in #210, so you can't see this warning now, because the file's encoding is "UTF-8" now.

**Comment by Bioruebe** [comment]
I make sure the encoding is correct before releasing an update, so you don't have to worry too much about getting it right :)

**Comment by wvxwxvw** [comment]
@SeaHOH 
I drag the file to the browser window, it should be similar to loading.

@Bioruebe 
OK

**Pull request merged**
