### PR TITLE
Update Russian.ini RC4

### PR DESCRIPTION
**Pull request by wvxwxvw**

### CODE REVIEW

**Comment by SeaHOH** [comment]
The right encoding of text is "UTF-16 LE + BOM".

**Comment by wvxwxvw** [comment]
[Russian.zip](https://github.com/Bioruebe/UniExtract2/files/5143754/Russian.zip)

**Comment by SeaHOH** [comment]
Its encoding is UTF-8 in [wvxwxvw:patch-3](https://github.com/wvxwxvw/UniExtract2/tree/patch-3), check line ending settings of your git.

**Comment by SeaHOH** [comment]
Maybe you edited it in web page, don't do this, use upload or git.

**Comment by wvxwxvw** [comment]
@SeaHOH No, I used the download. Now I'll try again.

**Pull request closed without merging**
