### PR TITLE
Create Latvian.ini

### PR DESCRIPTION
**Pull request by okass**
Added latvian translation for Universal Extractor

### CODE REVIEW

**Comment by DjDiabolik** [comment]
It's this project live at today ? It's be need a news version from months and months and all it's still in a limbo..........

**Comment by okass** [comment]
well atleast theres more translations :d

**Comment by DjDiabolik** [comment]
Yeah... i hope this move someone on developing.........

**Comment by Bioruebe** [comment]
Thanks for your Contribution.

@DjDiabolik It's still active, I just don't have much time to work on it these months.

**Pull request merged**
